/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gurock_smartinspect_Clock */

#ifndef _Included_com_gurock_smartinspect_Clock
#define _Included_com_gurock_smartinspect_Clock
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_gurock_smartinspect_Clock
 * Method:    getCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gurock_smartinspect_Clock_getCounter
  (JNIEnv *, jclass);

/*
 * Class:     com_gurock_smartinspect_Clock
 * Method:    getFrequency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gurock_smartinspect_Clock_getFrequency
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
